// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGtfe0RatNkFxkZMKq2vTlJW4Sx61fsmY',
    appId: '1:828822766357:web:ba9b10fa6bad89b97b9f1c',
    messagingSenderId: '828822766357',
    projectId: 'usocial-insta',
    authDomain: 'usocial-insta.firebaseapp.com',
    storageBucket: 'usocial-insta.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwaNlqrcVWUmUbB6Xy4i0Ie8htgMTyecY',
    appId: '1:828822766357:android:53b23dd49eaee1b97b9f1c',
    messagingSenderId: '828822766357',
    projectId: 'usocial-insta',
    storageBucket: 'usocial-insta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt8T5mNpwQH24573W9tEw1JThU_PdYdaA',
    appId: '1:828822766357:ios:c6d81427f62c72c47b9f1c',
    messagingSenderId: '828822766357',
    projectId: 'usocial-insta',
    storageBucket: 'usocial-insta.appspot.com',
    iosClientId: '828822766357-dhhkb80icfi55lkkjtbe3ss34b47qahj.apps.googleusercontent.com',
    iosBundleId: 'com.example.usocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt8T5mNpwQH24573W9tEw1JThU_PdYdaA',
    appId: '1:828822766357:ios:c6d81427f62c72c47b9f1c',
    messagingSenderId: '828822766357',
    projectId: 'usocial-insta',
    storageBucket: 'usocial-insta.appspot.com',
    iosClientId: '828822766357-dhhkb80icfi55lkkjtbe3ss34b47qahj.apps.googleusercontent.com',
    iosBundleId: 'com.example.usocial',
  );
}
